version: '3.3'
services:
  testrunner:
    image: maze_tf:latest
    ports:
      - "8000:5000"
    volumes:
      - ../var:/var/results
      - ../suites:/suites
    environment:
      - "PYTHONUNBUFFERED=1"
