version: '3.8'
services:
  testrunner:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/var/
    shm_size: '1g'
    ulimits:
        memlock: 1
        stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '3']
            capabilities: [gpu]