FROM tensorflow/tensorflow:latest-py3
WORKDIR /
COPY requirements.txt requirements.txt
COPY /src /src
COPY /setup.py /setup.py
COPY /README.md /README.md
COPY /LICENSE /LICENSE
COPY /testsuite_runner.py /testsuite_runner.py
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install -e .
CMD [ "python3", "testsuite_runner.py"]